version: '3.9'
services:
    shortgen:
        build: ./shortgen
        environment:
            - MONGO=mongo
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASS=${MONGO_PASS}
    shortsrv:
        build: ./shortsrv
        environment:
            - MONGO=mongo
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASS=${MONGO_PASS}
        ports: 
            - "8081:80"
    frontend:
        build: ./frontend
        environment:
            - MONGO=mongo
            - MONGO_USER=${MONGO_USER}
            - MONGO_PASS=${MONGO_PASS}
            - SHORTSRV=${SHORTSRV:-shortsrv}
        ports:
            - "80:80"

    mongo:
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
        ports:
            - "27018:27017"