version: '3.9'
services:
    shortgen:
        build: ./shortgen
        environment:
            - MONGO=mongo
    shortsrv:
        build: ./shortsrv
        environment:
            - MONGO=mongo
        ports: 
            - "8000:8080"
    frontend:
        build: ./frontend
        environment:
            - MONGO=mongo
        ports:
            - "8001:8080"

    mongo:
        image: mongo
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=example
        ports:
            - "27017:27017"