name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_PASS: ${{ secrets.MONGO_PASS }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: Start containers
      run: docker-compose up -d

    - name: Build frontend
      run: cd ./frontend && go build ./...
    
    - name: Test frontend
      run: cd ./frontend && go test ./...

    - name: Build shortgen
      run: cd ./shortgen && go build ./...
    
    - name: Test shortgen
      run: cd ./shortgen && go test ./...

    - name: Build shortsrv
      run: cd ./shortsrv && go build ./...
    
    - name: Test shortsrv
      run: cd ./shortsrv && go test ./...

    - name: Stop containers
      run: docker-compose down