name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env: 
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_PASS: ${{ secrets.MONGO_PASS }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: "Lint Frontend"
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        working-directory: ./src/frontend
        
    - name: "Lint Shortgen"
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        working-directory: ./src/shortgen
        
    - name: "Lint Shortsrv"
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        working-directory: ./src/shortsrv
        
    - name: Start containers
      run: docker-compose -f ./src/docker-compose.yml up -d; sleep 1;

    - name: CI Frontend
      run: make ci --directory ./src/frontend
    
    - name: CI Shortgen
      run: make ci --directory ./src/shortgen
    
    - name: CI Shortsrv
      run: make ci --directory ./src/shortsrv

    - name: Stop containers
      run: docker-compose down -f ./src/docker-compose.yml

    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
      env:
        GITHUB_REF: ${{ github.ref}}
    - run: |
        ref="$(echo ${GITHUB_REF} | cut -d'/' -f3)"
        echo GITHUB_REF - $ref
        docker build ./src/shortsrv -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/shortsrv:${ref}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/shortsrv:${ref}
        docker build ./src/shortgen -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/shortgen:${ref}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/shortgen:${ref}
        docker build ./src/frontend -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${ref}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:${ref}
