name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_PASS: ${{ secrets.MONGO_PASS }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: "Lint Frontend"
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        working-directory: ./src/frontend
        
    - name: "Lint Shortgen"
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        working-directory: ./src/shortgen
        
    - name: "Lint Shortsrv"
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        working-directory: ./src/shortsrv
        
    - name: Start containers
      run: docker-compose -f ./src/docker-compose.yml up -d; sleep 1;

    - name: CI Frontend
      run: make ci --directory ./src/frontend
    
    - name: CI Shortgen
      run: make ci --directory ./src/shortgen
    
    - name: CI Shortsrv
      run: make ci --directory ./src/shortsrv

    - name: Stop containers
      run: docker-compose down -f ./src/docker-compose.yml
