name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_PASS: ${{ secrets.MONGO_PASS }}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: "Setup golangci-lint"
      uses: nickhstr/action-setup-golangci-lint@v0.1.0
      with:
        version: 1.41.1
        
    - name: Start containers
      run: docker-compose up -d

    - name: Frontend
      run: make ci --directory ./frontend
    
    - name: Shortgen
      run: make ci --directory ./shortgen
    
    - name: Shortsrv
      run: make ci --directory ./shortsrv

    - name: Stop containers
      run: docker-compose down
