name: CI

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      MONGO_USER: ${{ secrets.MONGO_USER }}
      MONGO_PASS: ${{ secrets.MONGO_PASS }}
      MONGO: mongo
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
        
    - name: "Lint Frontend"
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        working-directory: ./frontend
        
    - name: "Lint Shortgen"
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        working-directory: ./shortgen
        
    - name: "Lint Shortsrv"
      uses: golangci/golangci-lint-action@v2.5.2
      with:
        working-directory: ./shortsrv
        
    - name: Start containers
      run: docker-compose up -d;

    - name: CI Frontend
      run: make ci --directory ./frontend
    
    - name: CI Shortgen
      run: make ci --directory ./shortgen
    
    - name: CI Shortsrv
      run: make ci --directory ./shortsrv

    - name: Stop containers
      run: docker-compose down
